import { GrantOpportunity } from '@/types';

export const CURATED_FRENCH_GRANTS: GrantOpportunity[] = [
  {
    title: 'FDVA 2 — Fonctionnement et projets innovants des associations',
    funder: 'Ministère de l’Éducation nationale et de la Jeunesse (DJEPVA)',
    url: 'https://www.associations.gouv.fr/le-fdva-fonctionnement-innovation.html',
    description:
      'Le Fonds pour le Développement de la Vie Associative (FDVA 2) soutient le fonctionnement global et les projets innovants des associations loi 1901 de tous secteurs, sans condition d’agrément ministériel préalable. Priorité aux petites et moyennes structures employeuses ou non.',
    funding_min: 1500,
    funding_max: 15000,
    currency: 'EUR',
    deadline: null,
    is_recurrent: true,
    recurrent_details: 'Campagne annuelle au 1er trimestre (janvier à mars selon les départements)',
    geographic_level: 'departement',
    eligible_regions: ['Toute la France', 'Île-de-France', 'Auvergne-Rhône-Alpes', 'Occitanie', 'Nouvelle-Aquitaine', 'Bretagne', 'Grand Est', 'Hauts-de-France'],
    eligible_departments: ['75', '93', '92', '94', '69', '13', '31', '33', '44', '59'],
    eligible_org_types: ['Association loi 1901'],
    themes: ['Vie associative', 'Solidarité', 'Culture', 'Environnement', 'Sport', 'Éducation'],
    beneficiaries: ['Tous publics'],
    requirements: [
      'Association régie par la loi 1901',
      'Siège social sur le territoire français',
      'Comptes financiers et rapport d’activité approuvés en AG',
      'Respect du Contrat d’Engagement Républicain (loi du 24 août 2021)',
    ],
    operating_history_required: 1,
    source_domain: 'associations.gouv.fr',
    source_id: 'fdva-2-national',
    status: 'curated',
    verified_at: new Date('2026-09-15'),
  },
  {
    title: 'FDVA 1 — Formation des bénévoles associatifs',
    funder: 'Délégation Régionale Académique à la Jeunesse, à l’Engagement et aux Sports (DRAJES)',
    url: 'https://www.associations.gouv.fr/le-fdva-formation-des-benevoles.html',
    description:
      'Aide financière destinée aux associations proposant des actions de formation au bénéfice de leurs bénévoles élus ou réguliers, afin d’accroître leurs compétences techniques, juridiques ou de gouvernance.',
    funding_min: 1000,
    funding_max: 10000,
    currency: 'EUR',
    deadline: null,
    is_recurrent: true,
    recurrent_details: 'Appel annuel régional',
    geographic_level: 'region',
    eligible_regions: ['Toute la France', 'Île-de-France', 'Auvergne-Rhône-Alpes', 'Occitanie'],
    eligible_org_types: ['Association loi 1901'],
    themes: ['Formation', 'Gouvernance', 'Numérique solidaire', 'Vie associative'],
    beneficiaries: ['Bénévoles', 'Dirigeants associatifs'],
    requirements: [
      'Programme de formation d’au moins une demi-journée',
      'Attestation de présence des bénévoles formés',
    ],
    operating_history_required: 1,
    source_domain: 'associations.gouv.fr',
    source_id: 'fdva-1-national',
    status: 'curated',
    verified_at: new Date('2026-09-15'),
  },
  {
    title: 'Transition écologique solidaire & Économie circulaire',
    funder: 'ADEME — Agence de la transition écologique',
    url: 'https://agirpourlatransition.ademe.fr/entreprises/aides-financieres',
    description:
      'Soutien financier aux initiatives associatives promouvant les circuits courts, la lutte contre le gaspillage, le réemploi d’objets et la sensibilisation citoyenne à l’empreinte carbone.',
    funding_min: 10000,
    funding_max: 60000,
    currency: 'EUR',
    deadline: new Date('2026-11-30'),
    is_recurrent: false,
    geographic_level: 'national',
    eligible_regions: ['Toute la France'],
    eligible_org_types: ['Association loi 1901', 'Fondation'],
    themes: ['Environnement', 'Climat', 'Biodiversité', 'Économie circulaire'],
    beneficiaries: ['Tous publics', 'Citoyens locaux'],
    requirements: [
      'Indicateurs d’impact carbone ou volume de déchets évités',
      'Plan de pérennité économique du modèle',
    ],
    operating_history_required: 1,
    source_domain: 'agirpourlatransition.ademe.fr',
    source_id: 'ademe-transition-eco',
    status: 'curated',
    verified_at: new Date('2026-09-20'),
  },
  {
    title: 'Fonds d’Action Sociale & Parentalité',
    funder: 'Caisse Nationale des Allocations Familiales (CNAF / CAF)',
    url: 'https://www.caf.fr/partenaires/partenaires-locaux',
    description:
      'Financement de projets associatifs renforçant le soutien à la parentalité, l’animation des espaces de vie sociale (EVS), l’accès aux vacances pour les familles défavorisées et la médiation familiale.',
    funding_min: 3000,
    funding_max: 35000,
    currency: 'EUR',
    deadline: null,
    is_recurrent: true,
    recurrent_details: 'Commission locale permanente des CAF départementales',
    geographic_level: 'departement',
    eligible_regions: ['Toute la France'],
    eligible_departments: ['75', '93', '69', '13', '31', '59'],
    eligible_org_types: ['Association loi 1901'],
    themes: ['Solidarité', 'Parentalité', 'Jeunesse', 'Action sociale'],
    beneficiaries: ['Familles', 'Enfants', 'Jeunes'],
    requirements: [
      'Convention d’objectifs et de financement avec la CAF locale',
      'Budget prévisionnel équilibré',
    ],
    operating_history_required: 1,
    source_domain: 'caf.fr',
    source_id: 'caf-action-sociale',
    status: 'curated',
    verified_at: new Date('2026-09-10'),
  },
  {
    title: 'Programme Déclics Jeunes & Solidarités de Proximité',
    funder: 'Fondation de France',
    url: 'https://www.fondationdefrance.org/fr/trouver-un-financement',
    description:
      'La Fondation de France accompagne les associations de terrain qui répondent aux urgences sociales de proximité : précarité alimentaire, rupture de lien social des aînés, inclusion par le logement et santé mentale.',
    funding_min: 5000,
    funding_max: 30000,
    currency: 'EUR',
    deadline: new Date('2026-10-31'),
    is_recurrent: true,
    recurrent_details: 'Sessions bisannuelles (printemps et automne)',
    geographic_level: 'national',
    eligible_regions: ['Toute la France'],
    eligible_org_types: ['Association loi 1901', 'Fondation'],
    themes: ['Solidarité', 'Santé mentale', 'Précarité', 'Logement'],
    beneficiaries: ['Personnes vulnérables', 'Seniors', 'Jeunes'],
    requirements: [
      'Organisme à but non lucratif éligible au mécénat (articles 200 et 238 bis du CGI)',
      'Action ancrée sur le territoire',
    ],
    operating_history_required: 2,
    source_domain: 'fondationdefrance.org',
    source_id: 'fdf-solidarite-proximite',
    status: 'curated',
    verified_at: new Date('2026-09-18'),
  },
  {
    title: 'Projet Sportif Fédéral (PSF) — Développement de la pratique solidaire',
    funder: 'Agence Nationale du Sport (ANS)',
    url: 'https://www.agencedusport.fr',
    description:
      'Subvention destinée aux clubs et associations sportives affiliées menant des actions d’insertion par le sport, de féminisation, de sport-santé ou d’accessibilité aux personnes en situation de handicap dans les quartiers prioritaires (QPV) et zones rurales (ZRR).',
    funding_min: 1500,
    funding_max: 12000,
    currency: 'EUR',
    deadline: null,
    is_recurrent: true,
    recurrent_details: 'Campagne annuelle fédérale au printemps',
    geographic_level: 'national',
    eligible_regions: ['Toute la France'],
    eligible_org_types: ['Association loi 1901'],
    themes: ['Sport', 'Santé', 'Handicap', 'Inclusion'],
    beneficiaries: ['Jeunes', 'Femmes', 'Personnes en situation de handicap', 'Habitants QPV'],
    requirements: [
      'Affiliation à une fédération sportive agréée',
      'Action ciblant prioritairement les territoires fragiles',
    ],
    operating_history_required: 1,
    source_domain: 'agencedusport.fr',
    source_id: 'ans-psf-national',
    status: 'curated',
    verified_at: new Date('2026-08-30'),
  },
  {
    title: 'Fonds d’Appui aux Initiatives Associatives Locales',
    funder: 'Région Île-de-France',
    url: 'https://www.iledefrance.fr/aides-et-appels-a-projets',
    description:
      'Aide financière régionale pour les projets associatifs franciliens renforçant la cohésion territoriale, la préservation du patrimoine vivant, l’aide alimentaire et l’engagement bénévole des jeunes.',
    funding_min: 5000,
    funding_max: 25000,
    currency: 'EUR',
    deadline: new Date('2026-12-15'),
    is_recurrent: true,
    recurrent_details: 'Appel annuel régional',
    geographic_level: 'region',
    eligible_regions: ['Île-de-France'],
    eligible_departments: ['75', '77', '78', '91', '92', '93', '94', '95'],
    eligible_org_types: ['Association loi 1901'],
    themes: ['Vie associative', 'Cohésion sociale', 'Culture', 'Solidarité'],
    beneficiaries: ['Franciliens', 'Jeunes', 'Bénévoles'],
    requirements: [
      'Siège ou activité principale situé en Île-de-France',
      'Cofinancement public/privé d’au moins 20 %',
    ],
    operating_history_required: 1,
    source_domain: 'iledefrance.fr',
    source_id: 'idf-initiatives-locales',
    status: 'curated',
    verified_at: new Date('2026-09-22'),
  },
  {
    title: 'Programme CERV — Citoyens, Égalité, Droits et Valeurs',
    funder: 'Commission Européenne',
    url: 'https://ec.europa.eu/info/funding-tenders/opportunities/portal/screen/programmes/cerv',
    description:
      'Financement européen d’envergure soutenant les organisations de la société civile engagées dans la promotion des droits fondamentaux, l’état de droit, la participation citoyenne et la lutte contre les violences faites aux femmes.',
    funding_min: 50000,
    funding_max: 200000,
    currency: 'EUR',
    deadline: new Date('2026-11-20'),
    is_recurrent: true,
    recurrent_details: 'Appels programmés sur le cadre financier pluriannuel 2021-2027',
    geographic_level: 'europe',
    eligible_regions: ['Toute la France', 'Union Européenne', 'Europe'],
    eligible_org_types: ['Association loi 1901', 'Fondation', 'ONG'],
    themes: ['Droits humains', 'Égalité', 'Citoyenneté', 'Démocratie'],
    beneficiaries: ['Citoyens européens', 'Femmes', 'Minorités'],
    requirements: [
      'Numéro PIC (Participant Identification Code) sur le portail de la Commission',
      'Partenariat transfrontalier recommandé ou impact national substantiel',
    ],
    operating_history_required: 2,
    source_domain: 'ec.europa.eu',
    source_id: 'eu-cerv-2026',
    status: 'curated',
    verified_at: new Date('2026-09-01'),
  },
  {
    title: 'Fonds d’Urgence et d’Accompagnement contre le Mal-Logement',
    funder: 'Fondation Abbé Pierre',
    url: 'https://www.fondation-abbe-pierre.fr',
    description:
      'Soutien aux associations qui gèrent des centres d’hébergement d’urgence, des pensions de famille, des ateliers d’auto-réhabilitation accompagnée et des haltes de jour pour personnes sans abri.',
    funding_min: 5000,
    funding_max: 40000,
    currency: 'EUR',
    deadline: null,
    is_recurrent: true,
    recurrent_details: 'Instruction continue au fil de l’eau par les délégations régionales',
    geographic_level: 'national',
    eligible_regions: ['Toute la France'],
    eligible_org_types: ['Association loi 1901', 'Fondation'],
    themes: ['Hébergement', 'Précarité', 'Solidarité', 'Droits humains'],
    beneficiaries: ['Sans-abri', 'Personnes mal-logées', 'Familles en précarité'],
    requirements: [
      'Projet respectant la dignité et l’inconditionnalité de l’accueil',
      'Rapport financier d’activité à jour',
    ],
    operating_history_required: 1,
    source_domain: 'fondation-abbe-pierre.fr',
    source_id: 'fap-mal-logement',
    status: 'curated',
    verified_at: new Date('2026-09-12'),
  },
];
